/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smarthome;

/**
 *
 * @author janel
 */
public class MainDashboard extends javax.swing.JFrame {

    private Device[] hub = {
        new SmartLight(),
        new Thermostat(),
        new SecurityCamera(),
        new SmartSpeaker(),
        new SmartLock(),
        new SecurityFloodlight()
    };
    private Device currentDevice = hub[0];

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
    initComponents();
    // Use your method to build the UI for the first device immediately
    updateDetailsPanel(hub[0]); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlNavigation = new javax.swing.JPanel();
        btnNavLight = new javax.swing.JButton();
        btnNavThermo = new javax.swing.JButton();
        btnNavCamera = new javax.swing.JButton();
        btnNavSpeaker = new javax.swing.JButton();
        btnNavLock = new javax.swing.JButton();
        btnNavFloodlight = new javax.swing.JButton();
        pnlControlCenter = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlSystemLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnClearLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 550));
        setPreferredSize(new java.awt.Dimension(600, 550));
        setResizable(false);

        pnlHeader.setBackground(new java.awt.Color(51, 51, 51));
        pnlHeader.setPreferredSize(new java.awt.Dimension(600, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Smart Home Dashboard");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                    .addContainerGap(11, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlNavigation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Select Device"));
        pnlNavigation.setMinimumSize(new java.awt.Dimension(140, 400));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(140, 400));
        pnlNavigation.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        btnNavLight.setText("Smart Light");
        btnNavLight.setMinimumSize(new java.awt.Dimension(140, 23));
        btnNavLight.setPreferredSize(new java.awt.Dimension(200, 23));
        btnNavLight.addActionListener(this::btnNavLightActionPerformed);
        pnlNavigation.add(btnNavLight);

        btnNavThermo.setText("Thermostat");
        btnNavThermo.addActionListener(this::btnNavThermoActionPerformed);
        pnlNavigation.add(btnNavThermo);

        btnNavCamera.setText("Security Camera");
        btnNavCamera.addActionListener(this::btnNavCameraActionPerformed);
        pnlNavigation.add(btnNavCamera);

        btnNavSpeaker.setText("Smart Speaker");
        btnNavSpeaker.addActionListener(this::btnNavSpeakerActionPerformed);
        pnlNavigation.add(btnNavSpeaker);

        btnNavLock.setText("Smart Lock");
        btnNavLock.addActionListener(this::btnNavLockActionPerformed);
        pnlNavigation.add(btnNavLock);

        btnNavFloodlight.setText("Security Floodlight");
        btnNavFloodlight.addActionListener(this::btnNavFloodlightActionPerformed);
        pnlNavigation.add(btnNavFloodlight);

        getContentPane().add(pnlNavigation, java.awt.BorderLayout.LINE_START);

        pnlControlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Control Panel"));
        pnlControlCenter.setPreferredSize(new java.awt.Dimension(120, 300));

        jButton3.setText("View State");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton1.setText("Modify Settings");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Execute");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Device: Smart Light");

        javax.swing.GroupLayout pnlControlCenterLayout = new javax.swing.GroupLayout(pnlControlCenter);
        pnlControlCenter.setLayout(pnlControlCenterLayout);
        pnlControlCenterLayout.setHorizontalGroup(
            pnlControlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlCenterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(191, 191, 191))
            .addGroup(pnlControlCenterLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel2)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlControlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlCenterLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlCenterLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(183, 183, 183))))
        );
        pnlControlCenterLayout.setVerticalGroup(
            pnlControlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlCenterLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(pnlControlCenter, java.awt.BorderLayout.CENTER);

        pnlSystemLog.setPreferredSize(new java.awt.Dimension(600, 200));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("System Ready...");
        jScrollPane1.setViewportView(jTextArea1);

        btnClearLog.setText("Clear Log");
        btnClearLog.addActionListener(this::btnClearLogActionPerformed);

        javax.swing.GroupLayout pnlSystemLogLayout = new javax.swing.GroupLayout(pnlSystemLog);
        pnlSystemLog.setLayout(pnlSystemLogLayout);
        pnlSystemLogLayout.setHorizontalGroup(
            pnlSystemLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSystemLogLayout.createSequentialGroup()
                .addContainerGap(524, Short.MAX_VALUE)
                .addComponent(btnClearLog)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        pnlSystemLogLayout.setVerticalGroup(
            pnlSystemLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSystemLogLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearLog)
                .addContainerGap())
        );

        getContentPane().add(pnlSystemLog, java.awt.BorderLayout.PAGE_END);

        setBounds(0, 0, 623, 516);
    }// </editor-fold>                        

    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jTextArea1.setText("System Ready...");
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }                                           

    private void btnNavLightActionPerformed(java.awt.event.ActionEvent evt) {                                            
        updateDetailsPanel(hub[0]);        // TODO add your handling code here:

    }                                           

    private void btnNavFloodlightActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        updateDetailsPanel(hub[5]);
    }                                                

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (currentDevice != null) {
        if (currentDevice.modifySettings(this)) {
            jTextArea1.append("\n[UPDATE] " + currentDevice.getName() + " settings changed.");
        }
    }
    }                                        

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (currentDevice != null) {
        jTextArea1.append("\n[STATE] " + currentDevice.getName() + ": " + currentDevice.viewState());
    }
    }                                        

    private void btnNavThermoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        updateDetailsPanel(hub[1]);
    }                                            

    private void btnNavCameraActionPerformed(java.awt.event.ActionEvent evt) {                                             
        updateDetailsPanel(hub[2]);
    }                                            

    private void btnNavSpeakerActionPerformed(java.awt.event.ActionEvent evt) {                                              
        updateDetailsPanel(hub[3]);
    }                                             

    private void btnNavLockActionPerformed(java.awt.event.ActionEvent evt) {                                           
        updateDetailsPanel(hub[4]);
    }                                          

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (currentDevice != null) {
        String result = currentDevice.execute();
        jTextArea1.append("\n[EXECUTE] " + currentDevice.getName() + ": " + result);
    }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnNavCamera;
    private javax.swing.JButton btnNavFloodlight;
    private javax.swing.JButton btnNavLight;
    private javax.swing.JButton btnNavLock;
    private javax.swing.JButton btnNavSpeaker;
    private javax.swing.JButton btnNavThermo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnlControlCenter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlSystemLog;
    // End of variables declaration                   

    private void updateDetailsPanel(Device device) {
        this.currentDevice = device; // Set the active device
    
    // Update the visual labels
    jLabel2.setText("Device: " + device.getName());
    pnlControlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Control Panel: " + device.getName()));
    
    }

}
